
-- ELIMINACION DE LA BASE DE DATOS SI ES QUE EXISTE

DROP DATABASE IF EXISTS appJava;


-- CREACION DE LA BASE DE DATOS
CREATE DATABASE appJava;

-- USO DE LA BASE DE DATOS
USE appJava;


-- CREACION DE LA TABLA TORNEOS
CREATE TABLE torneos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    fecha DATE NOT NULL,
    lugar VARCHAR(100) NOT NULL,
    nivel VARCHAR(50) NOT NULL,
    descripcion TEXT,
    estado VARCHAR(50) NOT NULL
);


-- MOSTRAR DATOS DE LA TABLA TORNEOS
SELECT * FROM torneos;


-- CREACION DE LA TABLA ESTUDIANTE
CREATE TABLE estudiantes (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    edad INT NOT NULL,
    dni VARCHAR(20) NOT NULL UNIQUE,
    correo VARCHAR(100) NOT NULL,
    celular VARCHAR(15) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    genero VARCHAR(10) NOT NULL
);



-- MOSTRAR DATOS DE LA TABLA ESTUDIANTE
SELECT * FROM estudiantes;


-- CREACION DE LA TABLA ENTRENADORES
CREATE TABLE entrenadores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    especialidad VARCHAR(100) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL
);


-- MOSTRAR DATOD DE LA TABLA ENTRENADORES
SELECT * FROM entrenadores;
